name: Update Fork

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0:00 执行一次

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Latest Code
      uses: actions/checkout@v2
      with:
        ref: upstream/master
    - name: Merge Latest Code
      run: |
        git remote add fork-origin https://github.com/ZhouWHao/juejin-helper.git
        git checkout master
        git merge upstream/master
    - name: Push Updated Code
      run: |
        git push fork-origin master
